spring:
  datasource:
    url: jdbc:h2:mem:librarydb

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true